### ISSUE TITLE
can not launch web

### ISSUE THREAD

**Issue by taozhiyuai** [neobundy/MLX-Stable-Diffusion-WebUI#4]
**I have installed and put models in dir. and ln to ./models

this is the error info on terminal.anyone can help?**

taozhiyu@TAOZHIYUdeMBP MLX-Stable-Diffusion-WebUI % ln -s ~/downloads/stable-diffusion-webui/models/Stable-diffusion ./models
taozhiyu@TAOZHIYUdeMBP MLX-Stable-Diffusion-WebUI % streamlit run main.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.31.217:8501

  For better performance, install the Watchdog module:

  $ xcode-select --install
  $ pip install watchdog
            
2024-03-13 08:13:48.365 Uncaught app exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/Users/taozhiyu/Downloads/MLX-Stable-Diffusion-WebUI/main.py", line 43, in <module>
    selected_model_without_extension = os.path.splitext(selected_model)[0]
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 118, in splitext
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by taozhiyuai** [comment]
on http://localhost:8501, the error info is the following


TypeError: expected str, bytes or os.PathLike object, not NoneType
Traceback:
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "/Users/taozhiyu/Downloads/MLX-Stable-Diffusion-WebUI/main.py", line 43, in <module>
    selected_model_without_extension = os.path.splitext(selected_model)[0]
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen posixpath>", line 118, in splitext

**Comment by neobundy** [comment]
The `./models` should be a symlink to a working Stable Diffusion Models directory. Don't just assume it's there. Check the path you've set up for it. You should see at least one *.safetensors model there. Note that `.models` should not be a normal file; it should be a `symlink`! If you have a normal file name `.models`, delete it and create a symlink to the correct directory.

Moreover, the first time you select a local safetensor model, the app converts it into a diffuser format, which takes some time. Wait for the `Generate` button to appear.

Once completed, local models function the same as HF diffuser models.

I've updated the codebase since HF's diffuser and MLX have been updated recently. Run `git pull` and try again. If you encounter the same error, it means your path is not set up correctly.

**Comment by taozhiyuai** [comment]
<img width="1779" alt="截屏2024-03-13 09 48 41" src="https://github.com/neobundy/MLX-Stable-Diffusion-WebUI/assets/146583103/6b784dc1-8137-4495-a0ec-6419bfbc6555">

look my screen copy. some SD directories there. I should move *.safetensors to "Stable-diffusion" dir. right?

**Comment by taozhiyuai** [comment]
the symlink I set:
<img width="864" alt="截屏2024-03-13 10 05 48" src="https://github.com/neobundy/MLX-Stable-Diffusion-WebUI/assets/146583103/0e3b4597-84db-476f-a483-ffdfdf183800">

the actual model is located:
<img width="1349" alt="截屏2024-03-13 10 06 51" src="https://github.com/neobundy/MLX-Stable-Diffusion-WebUI/assets/146583103/24be5cf2-219c-41e3-853c-73176078e710">
after running, the error info
<img width="697" alt="截屏2024-03-13 10 05 12" src="https://github.com/neobundy/MLX-Stable-Diffusion-WebUI/assets/146583103/3f0d04bd-5984-4931-9818-cbe100a1810a">
<img width="1673" alt="截屏2024-03-13 10 07 32" src="https://github.com/neobundy/MLX-Stable-Diffusion-WebUI/assets/146583103/8c1792d6-4775-4a33-9317-8a7228b098d0">

**Comment by neobundy** [comment]
Clicking on the `./models` symlink should lead you directly to the actual models directory.

Additionally, your setup is incorrect because the `Stable-diffusion` folder itself should contain `*.safetensors`, not its subdirectories. I didn't design it to recursively search for models across all subdirectories. It only scans the topmost directory: from `./models` to `Stable-diffusion`.

Ensure the symlink functions in both Finder and Terminal. If it doesn't, you might need to remove the symlink and create it again.
